Ceph: Update to Nautilus on CentOS and OracleLinux
The CentOS Stein OpenStack distribution depends on the Ceph Nautilus
release, while Kolla currently deploys Luminous on CentOS.

This change switches CentOS and OracleLinux builds to use Ceph Nautilus.

Support for auth UID has been removed in the Nautilus release [1][2], so
we have removed the --set-uid argument from calls to ceph-authtool.

FIXME: Currently, ceph-nfs is not building due to package conflicts:

--> Processing Dependency: liburcu-bp.so.1()(64bit) for package: nfs-ganesha-2.7.3-0.1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: nfs-ganesha-2.7.3-0.1.el7.x86_64 (nfs_ganesha)
           Requires: liburcu-bp.so.1()(64bit)
           Available: userspace-rcu-0.7.16-1.el7.x86_64 (epel)
               liburcu-bp.so.1()(64bit)
           Installing: userspace-rcu-0.10.0-3.el7.x86_64 (centos-ceph-nautilus)
              ~liburcu-bp.so.6()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[1] https://github.com/ceph/ceph/commit/d6def8ba1126209f8dcb40e296977dc2b09a376e
[2] http://docs.ceph.com/docs/master/releases/nautilus/

Change-Id: I000398f587c5f4d6cc8995e34e162eebc77bc3e3
Implements: blueprint centos-ceph-nautilus